version: '3'
services:
    app:
        build:
            context: .
            dockerfile: ./Dockerfile.test
        ports:
            - 7666:7666
        command: /opt/orbs/service --config /opt/orbs/config.json