version: '3'
services:
    app:
        build:
            context: .
            dockerfile: ./Dockerfile.test
        ports:
            - 8080
    static:
        build:
            context: .
            dockerfile: ./Dockerfile-static.test
        ports:
            - 80
    docker-host:
        image: qoomon/docker-host
        cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
        restart: on-failure
        ports: 
            - 7545