version: '3'
services:
    app:
        build:
            context: .
            dockerfile: ./Dockerfile.test
        ports:
            - 8080
        command: npm start -- --config /opt/orbs/config.json