version: '3'
services:
    app:
        build:
            context: .
            dockerfile: ./Dockerfile.test
        ports:
            - 8080
    static:
        build:
            context: .
            dockerfile: ./Dockerfile-static.test
        ports:
            - 80
